---
title: "RWorksheet_deluna#4"
author: "Nicole De Luna"
date: "2023-10-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#1

Household_Data <- data.frame(
  Shoe_size = c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0),
  Height = c(66.0,68.0,64.0,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.0,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0),
  Gender = c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
)
Household_Data
```

```{r}
#1a Describe the data
#The males shoe size and height are bigger/higher than the females.

#1b Create a subset by males and females with their corresponding shoe size and height. What its result?

male_shoeH <- subset(Household_Data, Gender == "M")

female_shoeH <- subset(Household_Data, Gender == "F")

   print(male_subset)
   print(female_subset)


```

```{r}
#1c  Find the mean of shoe size and height of the respondents. Write the R scripts and its result

meanshoeSH <- mean(Household_Data$Shoe_size&Household_Data$Height)
meanshoeSH
```

#1d Is there a relationship between shoe size and height? Why?

#Yes. The higher the height, the bigger the shoe size

#FACTORS

```{r}
#2
Monthsss <- c("March","April","January","November","January","September","October","September","November","August","January","November","November","February","May","August","July","December","August","August","September","November","February","April")
factor_months_vector <- factor(Monthsss)
factor_months_vector

```

```{r}

#3. Then check the summary() of the months_vector and factor_months_vector
summary(Monthsss)
summary(factor_months_vector)
#The result discplayed how mony of the same months are there in the vector and also displayed its data types. Yes they are both useful.

```

```{r}

#4 Create a vector and factor for the table below.

Direction <- c("East","West","North")
Frequency <- c(1,4,3)

factorDirect <- factor(Direction)
factorFreq <- factor(Frequency)

new_order_data <- factor(factorDirect,levels = c("East","West","North"))
print(new_order_data)

new_order_data2 <- factor(factorFreq,levels = c(1,4,3))
print(new_order_data2)

```

```{r}
#5. Enter the data below in Excel with file name = import_march.csv
#5a.
ExcelData <- read.csv("import_march.csv")
ExcelData

```

```{r}
#5b.
ExcelData

```

```{r}

#6a

inputNum <- readline(prompt="Enter number from 1 to 50:
                     ")
if(inputNum>50){
  print("The number is beyond the range of 1 to 50")
}else
{
  print("True")
}

```

```{r}
#7 Change

calculateMinBills <- function() {
 
  bills <- c(1000, 500, 200, 100, 50)
 
 
  amount <- as.numeric(readline("Enter the price of the snack (a multiple of 50 pesos): "))
 
  if (is.na(amount) || amount %% 50 != 0) {
    cat("Invalid input. Price must be a multiple of 50 pesos. ")
    return()
  }
 
  snackprice <- amount
 
 
  bill1000 <- 0
  bill500 <- 0
  bill200 <- 0
  bill100 <- 0
  bill50 <- 0

 
  if (snackprice >= 1000) {
    bill1000 <- snackprice %/% 1000
    snackprice <- snackprice %% 1000
  }
  if (snackprice >= 500) {
    bill500 <- snackprice %/% 500
    snackprice <- snackprice %% 500
  }
  if (snackprice >= 200) {
    bill200 <- snackprice %/% 200
    snackprice <- snackprice %% 200
  }
  if (snackprice >= 100) {
    bill100 <- snackprice %/% 100
    snackprice <- snackprice %% 100
  }
  if (snackprice >= 50) {
    bill50 <- snackprice %/% 50
  }


  cat("Price:", amount, "pesos")
  cat("Minimum number of bills needed:")
  cat("1000 pesos:", bill1000, "bills")
  cat("500 pesos:", bill500, "bills")
  cat("200 pesos:", bill200, "bills")
  cat("100 pesos:", bill100, "bills")
  cat("50 pesos:", bill50, "bills")
}

calculateMinBills()

```

```{r}

#8a Create a data frame
GradesMath <- data.frame(
    Name = c("Annie","Thea","Steve","Hanna"),
    Grade1 = c(85,65,75,95),
    Grade2 = c(65,75,55,75),
    Grade3 = c(85,90,80,100),
    Grade4 = c(100,90,85,90)
)
GradesMath

```

```{r}
#8b.Without using the rowMean function, output the average score of students whose average math score over 90 points during the semester.

GradesMath$Average <- (GradesMath$Grade1 + GradesMath$Grade2 + GradesMath$Grade3 + GradesMath$Grade4) / 4


HighGrades <-  GradesMath[GradesMath$Average > 90, ]

if(nrow(HighGrades)>0){
  print(HighGrades$Name,"'s average grade this semester is:",HighGrades)
}else{
  print("there is no student that got 90 average grades")
}

```

```{r}
#8c Without using the mean function, output as follows for the tests in which the average score was less than 80 out of 4 tests

 AverageScores <- colMeans(GradesMath[, -1])

if (AverageScores[1] < 80) {
    print("The 1st test was difficult.")
}else if (AverageScores[2] < 80) {
    print("The 2nd test was difficult.")
}else if (AverageScores[3] < 80) {
    print("The 3rd test was difficult.")
}else if (AverageScores[4] < 80) {
    print("The 4th test was difficult.")
}else{
  print("No test that students find it difficult")
}

```

```{r}
 #8d Without using the max function, output as follows for students whose highest score for a semester exceeds 90 points
 
 #Annie Scores
 
if (GradesMath[1,2] > GradesMath[1,3] && GradesMath[1,2] > GradesMath[1,4] && GradesMath[1,2] > GradesMath[1,5]) {
  AnnieScores <-GradesMath[1,2]
} else if (GradesMath[1,3] > GradesMath[1,4] && GradesMath[1,3] > GradesMath[1,5]) {
  AnnieScores <- GradesMath[1,3]
} else if (GradesMath[1,4] > GradesMath[1,5] && GradesMath[1,2] > GradesMath[1,5]) {
  AnnieScores <- GradesMath[1,4]
} else {
  AnnieScores <- GradesMath[1,5]
}




# Thea Scores
if (GradesMath[2,2] > GradesMath[2,3] && GradesMath[2,2] >GradesMath[2,4] && GradesMath[2,2] > GradesMath[2,5]) {
  TheaScores <- GradesMath[2,2]
} else if (GradesMath[2,3] > GradesMath[2,4] &&GradesMath[2,3] > GradesMath[2,5]) {
  theaScores <- mathgrades[2,3]
} else if (GradesMath[2,4] > GradesMath[2,5] && GradesMath[2,2] > GradesMath[2,5]) {
  TheaScores <- GradesMath[2,4]
} else {
  TheaScores <-GradesMath[2,5]
}



# Steve Scores
if (GradesMath[3,2] > GradesMath[3,3] &&GradesMath[3,2] > GradesMath[3,4] && GradesMath[3,2] >GradesMath[3,5]) {
  SteveScores <- GradesMath[3,2]
} else if (GradesMath[3,3] > GradesMath[3,4] && GradesMath[3,3] > GradesMath[3,5]) {
 SteveScores <- GradesMath[2,3]
} else if (GradesMath[3,4] > GradesMath[3,5] && GradesMath[3,2] > GradesMath[3,5]) {
  SteveScores <- GradesMath[3,4]
} else {
  SteveScores <- GradesMath[3,5]
}



# Hanna Scores
if (GradesMath[4,2] > GradesMath[4,3] && GradesMath[4,2] > GradesMath[4,4] && GradesMath[4,2] > GradesMath[4,5]) {
  HannaScores <- GradesMath[4,2]
} else if (GradesMath[4,3] > GradesMath[4,4] && GradesMath[4,3] > GradesMath[4,5]) {
  HannaScores <- mathgrades[2,3]
} else if (GradesMath[4,4] > GradesMath[4,5] && GradesMath[4,2] > GradesMath[4,5]) {
  HannaScores <- GradesMath[4,4]
} else {
  HannaScores <- GradesMath[4,5]
}

GradesMath$HighestGrades <- c(AnnieScores, TheaScores, SteveScores, HannaScores)


NinetyHighest <- GradesMath[GradesMath$HighestGrades > 90,]
NinetyHighest

if (nrow(NinetyHighest) > 0) {
  paste(NinetyHighest$Name, "'s highest grade this semester is", NinetyHighest$HighestGrade)
} else {
  paste("No students have an average math score over 90.")
}

```



